# Generated by Django 4.0.8 on 2025-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='avatars/default_1.png', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
