# Generated by Django 4.0.8 on 2025-04-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userinfo_birthday_alter_userinfo_avatar'),
    ]

    operations = [
    ]
